name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Compile main.c
        run: gcc main.c -o main
      - name: Run main with exit option
        # Ejecuta directamente la opción "7" para terminar el programa
        run: echo "7" | ./main
      - name: make
        run: make
      - name: make check
        run: make check
      - name: make distcheck
        run: make distcheck
